
title: Kishima's blog
description: >- # this means to ignore newlines until "baseurl:"
 Code and stuff

# Build settings
theme: minima
plugins:
  - jekyll-feed
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
